[workspace]
members = ["crates/*", "backend/*"]
default-members = ["backend/subscriptions"]
resolver = "3"

[workspace.package]
authors = ["Mustapha Annouaoui <mostafaanawawi@gmail.com>"]
edition = "2024"

[workspace.dependencies]
# Internals
model = { path = "./crates/model" }

# Externals
axum = "0.8.4"
serde = "1.0.219"
tokio = "1.47.1"
url = "2.5.4"
surrealdb = "2.3.7"
config = "0.15.13"
reqwest = "0.12.22"
rand = "0.9.2"
dotenvy = "0.15.7"
serde_json = "1.0.142"
surrealdb-migrations = "2.3.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tower = "0.5.2"
tower-http = "0.6.6"
thiserror = "2.0.12"
once_cell = "1.21.3"
http-body-util = "0.1.3"
mime = "0.3.17"
secrecy = "0.10.3"
include_dir = "0.7.4"