# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json

fileGroups:
  sources:
    - src/**/*
    - Cargo.toml
    - .env
  tests:
    - tests/**/*

tasks:
  build:
    command: cargo build
    description: Compile a local package and all of its dependencies
    local: true
    inputs:
      - "@globs(sources)"
  run:
    command: cargo run
    description: Run a binary or example of the local package
    local: true
    inputs:
      - "@globs(sources)"
  test:
    command: cargo test
    description: Execute all unit and integration tests and build examples of a local package
    inputs:
      - "@globs(sources)"
      - "@globs(tests)"
  bacon:
    command: bacon
    description: bacon watches your project and runs jobs in background
    preset: watcher
  check:
    command: cargo check
    description: Check a local package and all of its dependencies for errors
    inputs:
      - "@globs(sources)"
  fmt:
    command: cargo fmt
    description: This utility formats all bin and lib files of the current crate using rustfmt
    local: true
    inputs:
      - "@globs(sources)"
  fmt/check:
    extends: fmt
    local: false
    args: ["--check"]
  clippy:
    command: cargo clippy
    description: hecks a package to catch common mistakes and improve your Rust code
    local: true
    inputs:
      - "@globs(sources)"
  clippy/check:
    extends: clippy
    local: false
    args: ["--", "--deny", "warnings"]
