[package]
name = "model"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
surrealdb = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
url = { workspace = true, features = ["serde"] }
