name: Continuous Deployment

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_FILE_PATH: ./backend/subscriptions/Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      # This is required for advanced features like caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles(${{ env.DOCKER_FILE_PATH }}) }}

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: ${{ env.DOCKER_FILE_PATH }}
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKER_FILE_PATH }}
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/subscriptions:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
