name: Continuous Integration

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # Disable incremental compilation for faster from-scratch builds


jobs:
  check:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Set all GitHub variables as environment variables
        env:
          # Convert the repository variables context object to JSON
          VARS_CONTEXT_JSON: ${{ toJSON(vars) }}
          # Convert the repository secrets context object to JSON
          SECRETS_CONTEXT_JSON: ${{ toJSON(secrets) }}
        run: |
          # Use `jq` to parse and flatten the JSON objects into KEY=VALUE format
          echo "$VARS_CONTEXT_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo "$SECRETS_CONTEXT_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Check code for errors
        run: cargo check

      - name: Check code format
        run: cargo fmt --check

      - name: Check code for lint errors
        run: cargo clippy -- --deny warnings

      - name: Run tests
        run: cargo test
