name: Continuous Integration

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check code for errors
        run: cargo check

      - name: Check code format
        run: cargo fmt --check

      - name: Check code for lint errors
        run: cargo clippy -- --deny warnings

      - name: Run tests
        run: cargo test
