name: Continuous Integration

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cd
          cache-on-failure: true
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Set up toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Checks
        run: moon ci --color

      - name: Run report
        uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
