name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Debug
        run: env

      - name: Check code for errors
        run: cargo check

      - name: Check code format
        run: cargo fmt --check

      - name: Check code for lint errors
        run: cargo clippy -- --deny warnings

      - name: Run tests
        run: cargo test
